<?php use Phalcon\Tag as Tag ?>

<?php echo $this->getContent() ?>

<div align="right">
    <?php echo Tag::linkTo(array("companies/new", "Create film", "class" => "btn btn-primary")) ?>
</div>

<?php echo Tag::form(array("companies/search")) ?>

<div class="center scaffold">

    <h2>Search film</h2>

    <div class="clearfix">
        <label for="id">Id</label>
        <?php echo Tag::textField(array("id", "size" => 10, "maxlength" => 10, "type" => "number")) ?>
    </div>

    <div class="clearfix">
        <label for="name">Name</label>
        <?php echo Tag::textField(array("name", "size" => 24, "maxlength" => 70)) ?>
    </div>

    <div class="clearfix">
        <label for="type">Type</label>
        <?php echo Tag::textField(array("type", "size" => 10, "maxlength" => 30)) ?>
    </div>

    <div class="clearfix">
        <label for="actor">Actor</label>
        <?php echo Tag::textField(array("actor", "size" => 14, "maxlength" => 40)) ?>
    </div>

    <div class="clearfix">
        <label for="drector">Director</label>
        <?php echo Tag::textField(array("director", "size" => 14, "maxlength" => 40)) ?>
    </div>

    <div class="clearfix">
        <?php echo Tag::submitButton(array("Search", "class" => "btn btn-primary")) ?></td>
    </div>

</div>

</form>
