<?php use Phalcon\Tag as Tag ?>

<?php echo Tag::form("companies/create") ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo(array("companies", "&larr; Go Back")) ?>
    </li>
    <li class="pull-right">
        <?php echo Tag::submitButton(array("Save", "class" => "btn btn-success")) ?>
    </li>
</ul>

<?php echo $this->getContent() ?>

<div class="center scaffold">
    <h2>Create film</h2>

    <div class="clearfix">
        <label for="name">Name</label>
        <?php echo Tag::textField(array("name", "size" => 24, "maxlength" => 70)) ?>
    </div>

    <div class="clearfix">
        <label for="type">Type</label>
        <?php echo Tag::textField(array("type", "size" => 10, "maxlength" => 30)) ?>
    </div>

    <div class="clearfix">
        <label for="actor">Actors</label>
        <?php echo Tag::textField(array("actor", "size" => 14, "maxlength" => 40)) ?>
    </div>

    <div class="clearfix">
        <label for="director">Director</label>
        <?php echo Tag::textField(array("director", "size" => 14, "maxlength" => 40)) ?>
    </div>

</div>
</form>
