<p>
    <h2>ticket</h2>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>Number</td>
            <td>Name</td>
            <td>Date</td>
            <td>Total</td>
            <td>Status</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>51001</td>
            <td>Iron Man</td>
            <td>2012-04-02</td>
            <td align="right">12.50</td>
            <td><span class="label label-success">Success</span></td>
        </tr>
        <tr>
            <td>51002</td>
            <td>super man</td>
            <td>2012-04-04</td>
            <td align="right">22.75</td>
            <td><span class="label label-important">Rejected</span></td>
        </tr>
        <tr>
            <td>51003</td>
            <td>Ant Man</td>
            <td>2012-04-04</td>
            <td align="right">6.50</td>
            <td><span class="label label-success">Success</span></td>
        </tr>
        <tr>
            <td>51004</td>
            <td>the avenger</td>
            <td>2012-04-07</td>
            <td align="right">11.50</td>
            <td><span class="label label-success">Success</span></td>
        </tr>
    </tbody>
</table>

